name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Build Lib
        run: yarn lib:build

      - name: Copy Lib to Dist
        run: cp dist-lib/react-app-vite/* dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
